language: python
python:
  - "2.7"
install:
  - sudo apt-get install libboost-python-dev
  - easy_install http://hyriand.thegraveyard.org/PyV8-1.0_dev-py2.7-linux-x86_64.egg
  - python setup.py install
script:
  - python setup.py nosetests
