#! /usr/bin/env python

import ast
import os
from jaspyx.visitor import DefaultVisitor


if __name__ == '__main__':
    import sys

    if len(sys.argv) < 2:
        print >> sys.stderr, 'Syntax: %s <input>' % sys.argv[0]
        sys.exit(1)
    registry = {}
    c = ast.parse(open(sys.argv[1]).read(), sys.argv[1])
    registry['__main__'] = v = DefaultVisitor(sys.argv[1], registry)
    v.import_path = [os.path.split(sys.argv[1])[0]]
    v.visit(c)

    print '(function() {'
    print '  var modules = {},'
    print '      registry = {'
    for module, body in registry.items():
        print '    "%s": %s,' % (module, str(body.module))
    print '  };'
    print '  registry["__main__"]({'
    print '    __modules__: modules,'
    print '    __registry__: registry'
    print '  });'
    print '})();'
