#! /usr/bin/env python

import ast
import os
from jaspyx.visitor import DefaultVisitor


if __name__ == '__main__':
    import sys

    if len(sys.argv) < 2:
        print >> sys.stderr, 'Syntax: %s <input>' % sys.argv[0]
        sys.exit(1)
    registry = {}
    c = ast.parse(open(sys.argv[1]).read(), sys.argv[1])
    v = DefaultVisitor(sys.argv[1], registry)
    v.import_path = [os.path.split(sys.argv[1])[0]]
    v.visit(c)
    registry['__main__'] = str(v.module)

    print '(function() {'
    print '  var registry = {'
    for module, body in registry.items():
        print '    "%s": %s,' % (module, body)
    print '  };'
    print '  registry["__main__"]({ __registry__: registry });'
    print '})();'
