BUILTINS = {
    'undefined': 'undefined',
    'this': 'this',
    'arguments': 'arguments',
    'None': 'null',
    'window': 'window',
    'console': 'console',
    'True': 'true',
    'False': 'false',
    'alert': 'alert',
    'Object': 'Object',
    'Number': 'Number',
    'Boolean': 'Boolean',
    'String': 'String',
    'Array': 'Array',
    'Date': 'Date',
    'Math': 'Math',
    'RegExp': 'RegExp',
    'eval': 'eval',
    'int': 'parseInt',
    'float': 'parseFloat',
}
