BUILTINS = {
    'undefined': 'undefined',
    'None': 'null',
    'window': 'window',
    'True': 'true',
    'False': 'false',
    'alert': 'alert',
    'Object': 'Object',
    'Number': 'Number',
    'Boolean': 'Boolean',
    'String': 'String',
    'Array': 'Array',
    'Date': 'Date',
    'Math': 'Math',
    'RegExp': 'RegExp',
}
